"""
ser2net configuration generator.

Generates ser2net YAML configuration for exposing serial ports over TCP.
Supports ser2net 4.0+ YAML configuration format.
"""

from dataclasses import dataclass
from pathlib import Path

import yaml


@dataclass
class Ser2NetPort:
    """Configuration for a single ser2net port."""

    name: str
    device: str  # e.g., /dev/lab/sbc1-console
    tcp_port: int
    baud: int = 115200
    databits: int = 8
    parity: str = "none"  # none, even, odd
    stopbits: int = 1
    local: bool = True  # Only allow local connections
    kickolduser: bool = False  # Don't kick existing connections

    def to_ser2net_dict(self) -> dict:
        """Convert to ser2net YAML connection format."""
        # Build the connection string
        # Format: &name,baud,databits,parity,stopbits
        parity_char = {"none": "n", "even": "e", "odd": "o"}[self.parity.lower()]
        conn_str = f"{self.baud},{self.databits}{parity_char}{self.stopbits}"

        # Build options list
        options = []
        if self.local:
            options.append("local")
        if not self.kickolduser:
            options.append("-kickolduser")

        connection = {
            "accepter": f"tcp,{self.tcp_port}",
            "connector": f"serialdev,{self.device},{conn_str}",
            "enable": "on",
        }

        if options:
            connection["options"] = {opt: True for opt in options}

        return connection


def generate_ser2net_config(
    ports: list[Ser2NetPort],
    include_header: bool = True,
) -> str:
    """
    Generate ser2net YAML configuration from port list.

    Args:
        ports: List of Ser2NetPort configurations
        include_header: Include YAML header and comments

    Returns:
        YAML string for /etc/ser2net.yaml
    """
    output_lines = []

    if include_header:
        output_lines.extend(
            [
                "%YAML 1.1",
                "---",
                "# Lab Controller ser2net configuration",
                "# Generated by labctl",
                "#",
                "# Reload with: sudo systemctl restart ser2net",
                "# Test with: nc localhost <port>",
                "",
            ]
        )

    # Add each connection
    for port in ports:
        parity_char = {"none": "n", "even": "e", "odd": "o"}[port.parity.lower()]
        conn_str = f"{port.baud}{parity_char}{port.databits}{port.stopbits}"

        # Build options - local means only localhost connections
        local_spec = "localhost," if port.local else ""

        output_lines.append(f"connection: &{port.name}")
        output_lines.append(f"  accepter: tcp,{local_spec}{port.tcp_port}")
        output_lines.append(f"  connector: serialdev,{port.device},{conn_str},local")
        output_lines.append("  enable: on")
        output_lines.append("  options:")
        output_lines.append(
            f"    kickolduser: {'true' if port.kickolduser else 'false'}"
        )
        output_lines.append("")

    return "\n".join(output_lines)


def load_port_mapping(mapping_file: Path) -> list[dict]:
    """Load port mapping from YAML file."""
    with open(mapping_file) as f:
        data = yaml.safe_load(f)
    return data.get("ports", [])


def generate_from_mapping(
    mapping_file: Path,
    base_tcp_port: int = 3000,
    baud: int = 115200,
) -> str:
    """
    Generate ser2net config from udev port mapping file.

    Args:
        mapping_file: Path to port-mapping.yaml
        base_tcp_port: Starting TCP port number
        baud: Default baud rate

    Returns:
        ser2net YAML configuration string
    """
    ports_data = load_port_mapping(mapping_file)

    ports = []
    for i, port_info in enumerate(ports_data):
        name = port_info.get("name")
        if not name:
            continue

        port = Ser2NetPort(
            name=name,
            device=f"/dev/lab/{name}",
            tcp_port=base_tcp_port + i,
            baud=baud,
        )
        ports.append(port)

    return generate_ser2net_config(ports)


if __name__ == "__main__":
    # Example usage
    ports = [
        Ser2NetPort(
            name="sbc1-console",
            device="/dev/lab/sbc1-console",
            tcp_port=3001,
            baud=115200,
        ),
        Ser2NetPort(
            name="sbc2-console",
            device="/dev/lab/sbc2-console",
            tcp_port=3002,
            baud=115200,
        ),
    ]

    print(generate_ser2net_config(ports))
