"""
Udev rule generation for lab serial devices.

Generates and installs udev rules from the serial_devices database table,
creating /dev/lab/<name> symlinks for registered USB-serial adapters.
"""

import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from labctl.core.models import SerialDevice

UDEV_RULES_PATH = Path("/etc/udev/rules.d/99-lab-serial.rules")

UDEV_HEADER = """\
# Lab Controller Serial Device Rules
# Auto-generated by labctl - do not edit manually
# Regenerate with: labctl serial udev --install
"""


def generate_udev_rules(devices: list["SerialDevice"]) -> str:
    """Generate udev rules text from a list of serial devices."""
    lines = [UDEV_HEADER]

    for dev in sorted(devices, key=lambda d: d.name):
        comment_parts = []
        if dev.vendor:
            comment_parts.append(dev.vendor)
        if dev.model:
            comment_parts.append(dev.model)
        comment = f" ({', '.join(comment_parts)})" if comment_parts else ""

        lines.append(f"# {dev.name}{comment}")
        lines.append(
            f'SUBSYSTEM=="tty", KERNELS=="{dev.usb_path}", '
            f'SYMLINK+="lab/{dev.name}", MODE="0666"'
        )
        lines.append("")

    return "\n".join(lines)


def install_udev_rules(
    rules_text: str,
    rules_path: Path = UDEV_RULES_PATH,
) -> None:
    """Write udev rules to the system rules directory.

    Raises PermissionError if unable to write.
    """
    rules_path.write_text(rules_text)


def reload_udev() -> bool:
    """Reload udev rules and trigger device re-evaluation.

    Tries direct execution first, falls back to sudo if permission denied.
    Returns True on success.
    """
    for use_sudo in (False, True):
        try:
            prefix = ["sudo"] if use_sudo else []
            subprocess.run(
                [*prefix, "udevadm", "control", "--reload-rules"],
                check=True,
                capture_output=True,
            )
            subprocess.run(
                [*prefix, "udevadm", "trigger", "--subsystem-match=tty"],
                check=True,
                capture_output=True,
            )
            return True
        except subprocess.CalledProcessError:
            if not use_sudo:
                continue  # Retry with sudo
            return False
        except FileNotFoundError:
            return False
    return False


def discover_usb_serial() -> list[dict]:
    """Discover connected USB-serial devices by reading /sys.

    Returns a list of dicts with keys:
        device, path, usb_path, vendor, model, serial
    """
    devices = []
    tty_classes = [Path("/sys/class/tty")]

    for tty_dir in tty_classes:
        if not tty_dir.exists():
            continue
        for entry in sorted(tty_dir.iterdir()):
            name = entry.name
            if not (name.startswith("ttyUSB") or name.startswith("ttyACM")):
                continue

            device_link = entry / "device"
            if not device_link.exists():
                continue

            # Walk up to find the USB device path
            info = _get_udev_info(name)
            if info and info.get("usb_path"):
                devices.append(info)

    return devices


def _get_udev_info(tty_name: str) -> dict | None:
    """Get USB device info via udevadm."""
    try:
        result = subprocess.run(
            ["udevadm", "info", "--name", f"/dev/{tty_name}", "--attribute-walk"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode != 0:
            return None

        usb_path = None
        vendor = None
        model = None
        serial = None

        # udevadm --attribute-walk starts at the device and walks UP
        # to the root. We want the first (most specific) match for each field.
        for line in result.stdout.splitlines():
            line = line.strip()
            if line.startswith('KERNELS=="') and not line.startswith('KERNELS=="tty'):
                val = line.split('"')[1]
                # USB device paths look like "1-10.1.3"
                # Skip: PCI paths (0000:), interface descriptors (contain :),
                # and bare hub paths (no dot = just "1-12")
                if (
                    val
                    and "-" in val
                    and ":" not in val
                    and "." in val
                    and not val.startswith("0000:")
                    and usb_path is None
                ):
                    usb_path = val
            elif line.startswith('ATTRS{manufacturer}=="') and vendor is None:
                vendor = line.split('"')[1]
            elif line.startswith('ATTRS{product}=="') and model is None:
                model = line.split('"')[1]
            elif line.startswith('ATTRS{serial}=="') and serial is None:
                serial = line.split('"')[1]

        if not usb_path:
            return None

        return {
            "device": tty_name,
            "path": f"/dev/{tty_name}",
            "usb_path": usb_path,
            "vendor": vendor or "",
            "model": model or "",
            "serial": serial or "",
        }
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return None
