"""Unit tests for udev rule generation."""

from labctl.core.models import SerialDevice
from labctl.serial.udev import UDEV_HEADER, generate_udev_rules


class TestGenerateUdevRules:
    """Tests for generate_udev_rules function."""

    def test_empty_device_list(self):
        """Test generating rules with no devices."""
        result = generate_udev_rules([])
        assert result.startswith(UDEV_HEADER)
        # Only the header, no device-specific lines
        lines = result.strip().splitlines()
        header_lines = UDEV_HEADER.strip().splitlines()
        assert len(lines) == len(header_lines)

    def test_single_device(self):
        """Test generating rules for a single device."""
        device = SerialDevice(
            id=1,
            name="sbc1-console",
            usb_path="1-10.1.3",
            vendor="FTDI",
            model="FT232R",
        )
        result = generate_udev_rules([device])

        assert UDEV_HEADER in result
        assert "# sbc1-console (FTDI, FT232R)" in result
        assert (
            'SUBSYSTEM=="tty", KERNELS=="1-10.1.3", '
            'SYMLINK+="lab/sbc1-console", MODE="0666"'
        ) in result

    def test_multiple_devices_sorted_by_name(self):
        """Test that devices are sorted by name in output."""
        devices = [
            SerialDevice(id=1, name="z-device", usb_path="1-1.1"),
            SerialDevice(id=2, name="a-device", usb_path="1-1.2"),
            SerialDevice(id=3, name="m-device", usb_path="1-1.3"),
        ]
        result = generate_udev_rules(devices)

        lines = result.splitlines()
        comment_lines = [
            l
            for l in lines
            if l.startswith("# ")
            and not l.startswith("# Lab")
            and not l.startswith("# Auto")
            and not l.startswith("# Regen")
        ]
        assert len(comment_lines) == 3
        assert comment_lines[0] == "# a-device"
        assert comment_lines[1] == "# m-device"
        assert comment_lines[2] == "# z-device"

    def test_device_with_vendor_only(self):
        """Test comment format with only vendor set."""
        device = SerialDevice(
            id=1,
            name="test-dev",
            usb_path="2-1.1",
            vendor="Prolific",
        )
        result = generate_udev_rules([device])

        assert "# test-dev (Prolific)" in result

    def test_device_with_model_only(self):
        """Test comment format with only model set."""
        device = SerialDevice(
            id=1,
            name="test-dev",
            usb_path="2-1.1",
            model="PL2303",
        )
        result = generate_udev_rules([device])

        assert "# test-dev (PL2303)" in result

    def test_device_with_no_vendor_no_model(self):
        """Test comment format with no vendor or model."""
        device = SerialDevice(
            id=1,
            name="bare-dev",
            usb_path="3-1.1",
        )
        result = generate_udev_rules([device])

        # Comment should just be the name, no parentheses
        assert "# bare-dev\n" in result
        assert "()" not in result

    def test_rule_format_structure(self):
        """Test the overall structure of a generated rule block."""
        device = SerialDevice(
            id=1,
            name="my-adapter",
            usb_path="1-5.2.1",
            vendor="FTDI",
            model="FT4232H",
        )
        result = generate_udev_rules([device])
        lines = result.splitlines()

        # Find the device-specific lines (after header)
        device_lines = []
        found_header_end = False
        for line in lines:
            if found_header_end:
                device_lines.append(line)
            elif line == "" and device_lines == []:
                # Empty line after header could be separator; check next
                pass
            if line.startswith("# my-adapter"):
                found_header_end = True
                device_lines.append(line)

        # Should have: comment line, rule line, blank line
        assert len(device_lines) >= 2
        assert device_lines[0] == "# my-adapter (FTDI, FT4232H)"
        assert device_lines[1].startswith('SUBSYSTEM=="tty"')
        assert 'KERNELS=="1-5.2.1"' in device_lines[1]
        assert 'SYMLINK+="lab/my-adapter"' in device_lines[1]
        assert 'MODE="0666"' in device_lines[1]

    def test_header_content(self):
        """Test that the header contains expected content."""
        result = generate_udev_rules([])
        assert "Lab Controller Serial Device Rules" in result
        assert "Auto-generated by labctl" in result
        assert "do not edit manually" in result
        assert "labctl serial udev --install" in result
